export const LEADS_ADD_LOAD_END = 'LEADS_ADD_LOAD_END';
export const LEADS_ADD_ERROR = 'LEADS_ADD_ERROR';
export const LEADS_ADD_LOADING = 'LEADS_ADD_LOADING';
export const LEADS_ADD_CLEAR_ERROR = 'LEADS_ADD_CLEAR_ERROR';
export const LEAD_SET_CURRENT = 'LEAD_SET_CURRENT';
