export const EVENT_DETAIL_ERROR = 'EVENT_DETAIL_ERROR';
export const EVENT_DETAIL_CLEAR_ERROR = 'EVENT_DETAIL_CLEAR_ERROR';
export const EVENT_DETAIL_LOADING = 'EVENT_DETAIL_LOADING';
export const EVENT_DETAIL_LOAD_END = 'EVENT_DETAIL_LOAD_END';
export const EVENT_DETAIL_SET_CURRENT = 'EVENT_DETAIL_SET_CURRENT';
export const EVENT_DETAIL_WINNER_GENERATED = 'EVENT_DETAIL_WINNER_GENERATED';
export const TICKET_TOTALS = 'TICKET_TOTALS';
