export const LEAD_GROUP_ADD_LOAD_END = 'LEAD_GROUP_ADD_LOAD_END';
export const LEAD_GROUP_ADD_ERROR = 'LEAD_GROUP_ADD_ERROR';
export const LEAD_GROUP_ADD_LOADING = 'LEAD_GROUP_ADD_LOADING';
export const LEAD_GROUP_ADD_CLEAR_ERROR = 'LEAD_GROUP_ADD_CLEAR_ERROR';
export const ADD_LEADS_TO_GROUP = 'ADD_LEADS_TO_GROUP';
