export const LEAD_GROUP_LIST_LOAD_END = 'LEAD_GROUP_LIST_LOAD_END';
export const LEAD_GROUP_LIST_ERROR = 'LEAD_GROUP_LIST_ERROR';
export const LEAD_GROUP_LIST_LOADING = 'LEAD_GROUP_LIST_LOADING';
export const LEAD_GROUP_LIST_CLEAR_ERROR = 'LEAD_GROUP_LIST_CLEAR_ERROR';
