export const SCRIPTS_ERROR = "SCRIPTS_ERROR";
export const SCRIPTS_CLEAR_ERROR = "SCRIPTS_CLEAR_ERROR";
export const SCRIPTS_LOADING = "SCRIPTS_LOADING";
export const SCRIPTS_LOAD_END = "SCRIPTS_LOAD_END";
export const SCRIPTS_LIST_UPDATE = "SCRIPTS_LIST_UPDATE";
