export const CURRENT_QUESTION_LOAD_END = 'CURRENT_QUESTION_LOAD_END';
export const CURRENT_QUESTION_ERROR = 'CURRENT_QUESTION_ERROR';
export const CURRENT_QUESTION_LOADING = 'CURRENT_QUESTION_LOADING';
export const CURRENT_QUESTION_UPDATE =
  'CURRENT_QUESTION_UPDATE';
export const CURRENT_SCRIPT_FETCH_LOAD_END = 'CURRENT_SCRIPT_FETCH_LOAD_END';
export const CURRENT_SCRIPT_FETCH_ERROR = 'CURRENT_SCRIPT_FETCH_ERROR';
export const CURRENT_SCRIPT_FETCH_LOADING = 'CURRENT_SCRIPT_FETCH_LOADING';
export const CURRENT_SCRIPT_UPDATE =
  'CURRENT_SCRIPT_UPDATE';
export const FETCH_SCRIPT_ERROR = 'FETCH_SCRIPT_ERROR';
export const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';
export const QUESTIONS_UPDATE = 'QUESTIONS_UPDATE';
export const CREATING_NEW_QUESTION_UPDATE = 'CREATING_NEW_QUESTION_UPDATE';
export const UPDATE_CURRENT_ANSWER = 'UPDATE_CURRENT_ANSWER';
