export const LEADS_LIST_LOAD_END = 'LEADS_LIST_LOAD_END';
export const LEADS_LIST_ERROR = 'LEADS_LIST_ERROR';
export const LEADS_LIST_LOADING = 'LEADS_LIST_LOADING';
export const LEADS_LIST_CLEAR_ERROR = 'LEADS_LIST_CLEAR_ERROR';
export const LEAD_LIST_UPDATE = 'LEAD_LIST_UPDATE';
