export const UPDATE_CURRENT_SCRIPT = 'UPDATE_CURRENT_SCRIPT';
export const UPDATE_CURRENT_QUESTION = 'UPDATE_CURRENT_QUESTION';
export const CALL_ERROR = "CALL_ERROR";
export const CALL_CLEAR_ERROR = "CALL_CLEAR_ERROR";
export const CALL_LOADING = "CALL_LOADING";
export const CALL_LOAD_END = "CALL_LOAD_END";
export const CALL_UPDATE = 'CALL_UPDATE';
export const CURRENT_QUESTION_UPDATE = 'CURRENT_QUESTION_UPDATE';
