export const AGENTS_ADD_LOAD_END = 'AGENTS_ADD_LOAD_END';
export const AGENTS_ADD_ERROR = 'AGENTS_ADD_ERROR';
export const AGENTS_ADD_LOADING = 'AGENTS_ADD_LOADING';
export const AGENTS_ADD_CLEAR_ERROR =
  'AGENTS_ADD_CLEAR_ERROR';
