export const AGENT_PROFILE_UPDATE_LOAD_END = 'AGENT_PROFILE_UPDATE_LOAD_END';
export const AGENT_PROFILE_UPDATE_ERROR = 'AGENT_PROFILE_UPDATE_ERROR';
export const AGENT_PROFILE_UPDATE_LOADING = 'AGENT_PROFILE_UPDATE_LOADING';
export const AGENT_PROFILE_UPDATE_CLEAR_ERROR =
  'AGENT_PROFILE_UPDATE_CLEAR_ERROR';
