export const AGENTS_LIST_LOAD_END = 'AGENTS_LIST_LOAD_END';
export const AGENTS_LIST_ERROR = 'AGENTS_LIST_ERROR';
export const AGENTS_LIST_LOADING = 'AGENTS_LIST_LOADING';
export const AGENTS_LIST_CLEAR_ERROR =
  'AGENTS_LIST_CLEAR_ERROR';
