export const RAFFLE_LOAD_END = 'RAFFLE_LOAD_END';
export const RAFFLE_CREATE_ERROR = 'RAFFLE_CREATE_ERROR';
export const RAFFLE_CLEAR_ERROR = 'RAFFLE_CLEAR_ERROR';
export const RAFFLE_LOADING = 'RAFFLE_LOADING';
export const RAFFLE_CLEAR_FIELDS = 'RAFFLE_CLEAR_FIELDS';
export const RAFFLE_LIST = 'RAFFLE_LIST';
