export const PROFILE_UPDATE_LOAD_END = 'PROFILE_UPDATE_LOAD_END';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';
export const PROFILE_UPDATE_LOADING = 'PROFILE_UPDATE_LOADING';
export const PROFILE_UPDATE_CLEAR_ERROR = 'PROFILE_UPDATE_CLEAR_ERROR';
