export const GUIDE_LOAD_END = 'GUIDE_LOAD_END';
export const GUIDE_CREATE_ERROR = 'GUIDE_CREATE_ERROR';
export const GUIDE_CLEAR_ERROR = 'GUIDE_CLEAR_ERROR';
export const GUIDE_LOADING = 'GUIDE_LOADING';
