export const LEAD_DETAIL_LOADING = "LEAD_DETAIL_LOADING";
export const LEAD_DETAIL_LOAD_END = "LEAD_DETAIL_LOAD_END";
export const LEAD_DETAIL_UPDATE = "LEAD_DETAIL_UPDATE";
export const LEAD_DETAIL_CLEAR_ERROR = "LEAD_DETAIL_CLEAR_ERROR";
export const LEAD_DETAIL_ERROR = "LEAD_DETAIL_ERROR";
