export const BROKER_PROFILE_UPDATE_LOAD_END = 'BROKER_PROFILE_UPDATE_LOAD_END';
export const BROKER_PROFILE_UPDATE_ERROR = 'BROKER_PROFILE_UPDATE_ERROR';
export const BROKER_PROFILE_UPDATE_LOADING = 'BROKER_PROFILE_UPDATE_LOADING';
export const BROKER_PROFILE_UPDATE_CLEAR_ERROR =
  'BROKER_PROFILE_UPDATE_CLEAR_ERROR';
